title = 'Authentication'
grab_keyboard = false
show_hostname = false
resizable = false
depth = 32

[dialog]
font = "Source Code Pro 10"
font_file = 'none'
direction = 'none'
label = 'Enter your password'
alignment = 'Left'
scale = 'none'
indicator_label = ''
input_timeout = 30
foreground = '#c5c8c6'
background = '#1d1f21'

[dialog.layout_opts]
layout = 'Center'
horizontal_spacing = 'none'
vertical_spacing = 'none'
text_width = 'none'

[dialog.ok_button]
label = 'OK'
foreground = '#c5c8c6'
horizontal_spacing = 'none'
vertical_spacing = 'none'
border_width = 1.0
radius_x = 3
radius_y = 3
pressed_adjustment_x = 0
pressed_adjustment_y = 0
background = '#343638'
border_color = '#343638'
border_color_pressed = '#1d1f21'
background_stop = 'none'
background_pressed = '#1d1f21'
background_pressed_stop = 'none'
background_hover_stop = 'none'
background_hover = '#343638'

[dialog.cancel_button]
label = 'Cancel'
foreground = '#c5c8c6'
horizontal_spacing = 'none'
vertical_spacing = 'none'
border_width = 1.0
radius_x = 3
radius_y = 3
pressed_adjustment_x = 0
pressed_adjustment_y = 0
background = '#343638'
border_color = '#343638'
border_color_pressed = '#1d1f21'
background_stop = 'none'
background_pressed = '#1d1f21'
background_pressed_stop = 'none'
background_hover_stop = 'none'
background_hover = '#343638'

[dialog.clipboard_button]
foreground = '#c5c8c6'
horizontal_spacing = 'none'
vertical_spacing = 'none'
border_width = 1.0
radius_x = 3
radius_y = 3
pressed_adjustment_x = 0
pressed_adjustment_y = 0
background = '#343638'
border_color = '#343638'
border_color_pressed = '#1d1f21'
background_stop = 'none'
background_pressed = '#1d1f21'
background_pressed_stop = 'none'
background_hover_stop = 'none'
background_hover = '#343638'

[dialog.indicator]
border_width = 1.0
blink = false
background = '#343638'
background_stop = 'none'
border_color_focused = '#343638'
indicator_color = '#00ff00'
indicator_color_stop = 'none'
type = 'Circle'

[dialog.indicator.circle]
diameter = 'none'
rotate = true
rotation_speed_start = 0.1
rotation_speed_gain = 1.05
light_up = false
spacing_angle = 0.5
indicator_count = 3
indicator_width = 8
lock_color = '#c5c8c6'
