#!/bin/bash

update_dpi() {
    echo "Xft.dpi: $1" | xrdb -merge
    echo "Xft/DPI $(expr $1 \* 1024)" > ~/.xsettingsd
    echo "Gtk/CursorThemeSize $2" >> ~/.xsettingsd
    sed -i -E "s/height = .*?/height = $3/g" ~/.config/polybar/config
    sed -i -E "s/font: .*?/font: \"URWGothicBook $4\";/g" ~/.config/rofi/config.rasi
    killall -HUP xsettingsd
}

if nvidia-settings -q CurrentMetaMode | grep DPY-3 > /dev/null; then
    nvidia-settings --assign CurrentMetaMode="HDMI-0: 3840x2160_60+0+0 {ForceFullCompositionPipeline=On}" > /dev/null
    update_dpi 192 32 50 14

    sleep 1
    pactl set-default-sink alsa_output.pci-0000_01_00.1.hdmi-stereo
else
    nvidia-settings --assign CurrentMetaMode="DP-2: 2560x1440_120 +0+0 {ForceFullCompositionPipeline=On}" > /dev/null
    update_dpi 108 16 30 10

    sleep 1
    pactl set-default-sink alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-output
fi

# why restart?
nitrogen --set-zoom-fill ~/.wallpapers/wallpaper.jpeg
systemctl --user restart dunst
