#!/bin/bash

set -x

update_dpi() {
    echo "Xft.dpi: $1" | xrdb -merge
    echo "Xft/DPI $(expr $1 \* 1024)" > ~/.xsettingsd
    echo "Gtk/CursorThemeSize $2" >> ~/.xsettingsd
    killall -HUP xsettingsd
    i3-msg restart
}

if nvidia-settings -q CurrentMetaMode | grep DPY-3 > /dev/null; then
    nvidia-settings --assign CurrentMetaMode="HDMI-0: 3840x2160_60+0+0 {ForceFullCompositionPipeline=On}" > /dev/null
    sed -i -E 's/height = .*?/height = 50/g' ~/.config/polybar/config
    sed -i -E 's/tray-maxsize = .*?/tray-maxsize = 40/g' ~/.config/polybar/config
    sed -i -E 's/font: .*?/font: "URWGothicBook 14";/g' ~/.config/rofi/config.rasi
    update_dpi 192 32

    nitrogen --restore
    pactl set-default-sink alsa_output.pci-0000_06_00.1.hdmi-stereo
else
    nvidia-settings --assign CurrentMetaMode="DP-2: 2560x1440_120 +0+0 {ForceFullCompositionPipeline=On}" > /dev/null
    sed -i -E 's/height = .*?/height = 30/g' ~/.config/polybar/config
    sed -i -E 's/tray-maxsize = .*?/tray-maxsize = 20/g' ~/.config/polybar/config
    sed -i -E 's/font: .*?/font: "URWGothic Book 10";/g' ~/.config/rofi/config.rasi
    update_dpi 108 16

    nitrogen --restore
    pactl set-default-sink alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-output
fi
