#!/bin/zsh

declare -i timeout=30
HASS_KEY=$(cat ~/.secrets/HASS_KEY.secret)

update_state() {
  curl -X POST -H "Authorization: Bearer ${HASS_KEY}" \
  -H "Content-Type: application/json" \
  -d "{\"state\": \"$1\"}" \
  https://homeassistant.prephyte.ru/api/states/binary_sensor.pc
}

revert() {
    update_state on
    xset dpms 0 0 0
    xset -dpms
    sleep 0.6
    i3-msg restart
}

fast_sleep() {
    update_state off
    xset dpms force off
    sleep 1
    for _ in {1..$(( ($timeout - 1) * 5 ))}; do
        if [ $(xprintidle) -lt 400 ]; then
            revert
            exit 0
        fi
        sleep 0.2
        xset dpms force off
    done
}

trap revert HUP INT TERM
xset +dpms dpms $timeout $timeout $timeout
fast_sleep
setxkbmap us
~/.scripts/i3lock-fancy -n -e
revert
