#!/bin/zsh

declare -i timeout=30

revert() {
    xset dpms 0 0 0
    xset -dpms
    sleep 0.6
    i3-msg restart
}

fast_sleep() {
    xset dpms force off
    sleep 1
    for _ in {1..$(( ($timeout - 1) * 5 ))}; do
        if [ $(xprintidle) -lt 400 ]; then
            revert
            exit 0
        fi
        sleep 0.2
        xset dpms force off
    done
}

trap revert HUP INT TERM
xset +dpms dpms $timeout $timeout $timeout
fast_sleep
# ~/.scripts/i3lock-fancy -n -e -k
~/.scripts/i3lock-fancy -n -e
revert
