#!/bin/sh

get_icon() {
    case $1 in
        01d) icon="";;
        01n) icon="";;
        02d) icon="";;
        02n) icon="";;
        03d) icon="";;
        03n) icon="";;
        04*) icon="";;
        09*) icon="";;
        10*) icon="";;
        11*) icon="";;
        13*) icon="";;
        50*) icon="";;
        *) icon="";
    esac
    echo $icon
}

KEY="e4cda77ae637b2e9bfdf5ef0a40ce8f5"
CITY="Podolsk"
UNITS="metric"
SYMBOL="°"

API="https://api.openweathermap.org/data/2.5"

CITY_PARAM="q=$CITY"

current=$(curl -sf "$API/weather?appid=$KEY&$CITY_PARAM&units=$UNITS")
forecast=$(curl -sf "$API/forecast?appid=$KEY&$CITY_PARAM&units=$UNITS&cnt=1")

if [ -n "$current" ] && [ -n "$forecast" ]; then
    current_temp=$(echo "$current" | jq ".main.temp" | cut -d "." -f 1)
    current_icon=$(echo "$current" | jq -r ".weather[0].icon")

    forecast_temp=$(echo "$forecast" | jq ".list[].main.temp" | cut -d "." -f 1)
    forecast_icon=$(echo "$forecast" | jq -r ".list[].weather[0].icon")

    # echo "$(get_icon "$current_icon") $current_temp$SYMBOL  $(get_icon "$forecast_icon") $forecast_temp$SYMBOL"
    echo "$(get_icon "$current_icon") $current_temp$SYMBOL"
fi
